# theme: jekyll-theme-minimal
defaults:
  -
    scope:
      path: ""
    values:
      layout: "minimal"

title: Python Best Practices

description: 
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal